services:
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092/tcp
  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://openserach-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    ports:
      - 9200:9200/tcp # REST API
      # - 9300:9300/tcp
      - 9600:9600/tcp # Performance Analyzer
      # - 9650:9650/tcp
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    environment:
      - cluster.name=opensearch-cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - node.name=opensearch-node1
      # - discovery.type=single-node
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS="-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=str0ngp@ssword
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    ports:
      - 9200:9200/tcp # REST API
      - 9600:9600/tcp # Performance Analyzer
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    environment:
      - node.name=opensearch-node2
      - cluster.name=opensearch-cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      # - discovery.type=single-node
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS="-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=str0ngp@ssword
volumes:
  opensearch-data1:
  opensearch-data2:
networks:
  opensearch-net: